name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily
  workflow_dispatch:       # lets you run it manually

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate profile cards
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
